import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //    {/* <ThemeModeScript /> */}
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     <Header />
    //     {children}
    //   </body>
    // </html>
    <html>
    <head>
      <ThemeModeScript />
    </head>
    <body className="dark:bg-slate-900 bg-gray-200">
      {" "}
      <Flowbite>
      <Header />
        {children}

        {/* <DarkThemeToggle /> */}

        <Toaster />
      </Flowbite>
    </body>
  </html>
  );
}
